### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by sadig41** [babymotte/jgitfx#1]
Hi,
I try to build the project on Eclipse and Neatbans but i can not.
thanks

**Comment by babymotte** [comment]
Hi,
thanks for your interest in my project. I'm currently restructuring the project into an OSGi application because it got a bit intransparent for my taste. For that I'm moving to new repositories at https://github.com/jgitfx. I haven't paid too much attention to the original codebase since but it will not be maintained anyway, so if you are interested in the progress of the project I would recommend looking at the new repos.
The build process of the new repos isn't really refined yet and most of the functionality of the original codebase has not been migrated yet. As I wrote this is all still VERY early alpha stage :)

If you have maven installed, you can run the application from the new codebase like this:

```git clone https://github.com/jgitfx/net.bbmsoft.jgitfx.application.git
cd net.bbmsoft.jgitfx.application
mvn
java -jar target/net.bbmsoft.jgitfx.application.jar```

But you will not see much more than an empty frame since like I said most of the functionality is not migrated yet.

To build/run in eclipse, make sure you have Bndtools installed, then clone all repositories from https://github.com/jgitfx into ONE directory (that's important!), import them into eclipse (cnf has an eclipse .project file, the others you will have to import as maven projects) and then select all imported projects, right click and select `Configure > Add Bndtools Project Nature`. Then you should be able to run net.bbmsoft.jgitfx.application/net.bbmsoft.jgitfx.application.bndrun. Like I said, not really refined yet ;)

I don't know if there is a bnd plugin for netbeans so I'm afraid I can't help with that.

Hope that helped.

**Comment by babymotte** [comment]
You will now find a detailed and up to date description of how to build in https://github.com/jgitfx/net.bbmsoft.jgitfx.parent Please discuss any further issues there.

This repository is now obsolete and will be deleted in the near future.
